/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A key=value combination to allow for further triggering of rules or redirects.
 * @export
 * @interface CustomParameterDto
 */
export interface CustomParameterDto {
    /**
     * Key of the custom parameter.
     * @type {string}
     * @memberof CustomParameterDto
     */
    key: string;
    /**
     * Value of the custom parameter
     * @type {string}
     * @memberof CustomParameterDto
     */
    value: string;
}

/**
 * Check if a given object implements the CustomParameterDto interface.
 */
export function instanceOfCustomParameterDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function CustomParameterDtoFromJSON(json: any): CustomParameterDto {
    return CustomParameterDtoFromJSONTyped(json, false);
}

export function CustomParameterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomParameterDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function CustomParameterDtoToJSON(value?: CustomParameterDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': value.value,
    };
}

