/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomParameterTrigger
 */
export interface CustomParameterTrigger {
    /**
     * 
     * @type {string}
     * @memberof CustomParameterTrigger
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof CustomParameterTrigger
     */
    value: string;
}

/**
 * Check if a given object implements the CustomParameterTrigger interface.
 */
export function instanceOfCustomParameterTrigger(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function CustomParameterTriggerFromJSON(json: any): CustomParameterTrigger {
    return CustomParameterTriggerFromJSONTyped(json, false);
}

export function CustomParameterTriggerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomParameterTrigger {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function CustomParameterTriggerToJSON(value?: CustomParameterTrigger | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': value.value,
    };
}

