/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Contains debug info associated to response.
 * @export
 * @interface DebugDto
 */
export interface DebugDto {
    /**
     * Search request in raw format executed internally against search engine.
     * @type {Array<object>}
     * @memberof DebugDto
     */
    rawSearchRequest?: Array<object>;
    /**
     * Search response in raw format received internally from search engine.
     * @type {Array<object>}
     * @memberof DebugDto
     */
    rawSearchResponse?: Array<object>;
}

/**
 * Check if a given object implements the DebugDto interface.
 */
export function instanceOfDebugDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DebugDtoFromJSON(json: any): DebugDto {
    return DebugDtoFromJSONTyped(json, false);
}

export function DebugDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebugDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rawSearchRequest': !exists(json, 'rawSearchRequest') ? undefined : json['rawSearchRequest'],
        'rawSearchResponse': !exists(json, 'rawSearchResponse') ? undefined : json['rawSearchResponse'],
    };
}

export function DebugDtoToJSON(value?: DebugDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rawSearchRequest': value.rawSearchRequest,
        'rawSearchResponse': value.rawSearchResponse,
    };
}

