/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RuleVariant } from './RuleVariant';
import {
    RuleVariantFromJSON,
    RuleVariantFromJSONTyped,
    RuleVariantToJSON,
} from './RuleVariant';

/**
 * 
 * @export
 * @interface ExperimentVariant
 */
export interface ExperimentVariant {
    /**
     * 
     * @type {string}
     * @memberof ExperimentVariant
     */
    name: string;
    /**
     * 
     * @type {RuleVariant}
     * @memberof ExperimentVariant
     */
    ruleVariant: RuleVariant;
    /**
     * 
     * @type {number}
     * @memberof ExperimentVariant
     */
    variantTriggerPercentage: number;
}

/**
 * Check if a given object implements the ExperimentVariant interface.
 */
export function instanceOfExperimentVariant(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "ruleVariant" in value;
    isInstance = isInstance && "variantTriggerPercentage" in value;

    return isInstance;
}

export function ExperimentVariantFromJSON(json: any): ExperimentVariant {
    return ExperimentVariantFromJSONTyped(json, false);
}

export function ExperimentVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentVariant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ruleVariant': RuleVariantFromJSON(json['ruleVariant']),
        'variantTriggerPercentage': json['variantTriggerPercentage'],
    };
}

export function ExperimentVariantToJSON(value?: ExperimentVariant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'ruleVariant': RuleVariantToJSON(value.ruleVariant),
        'variantTriggerPercentage': value.variantTriggerPercentage,
    };
}

