/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Retrievable fields.
 * @export
 * @interface FieldMask
 */
export interface FieldMask {
    /**
     * Paths for retrievable fields (array).
     * @type {Array<string>}
     * @memberof FieldMask
     */
    paths?: Array<string>;
}

/**
 * Check if a given object implements the FieldMask interface.
 */
export function instanceOfFieldMask(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FieldMaskFromJSON(json: any): FieldMask {
    return FieldMaskFromJSONTyped(json, false);
}

export function FieldMaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldMask {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paths': !exists(json, 'paths') ? undefined : json['paths'],
    };
}

export function FieldMaskToJSON(value?: FieldMask | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'paths': value.paths,
    };
}

