/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilterParameter
 */
export interface FilterParameter {
    /**
     * 
     * @type {string}
     * @memberof FilterParameter
     */
    field: string;
    /**
     * 
     * @type {string}
     * @memberof FilterParameter
     */
    value?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FilterParameter
     */
    exclude: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FilterParameter
     */
    derivedFromProduct: boolean;
}

/**
 * Check if a given object implements the FilterParameter interface.
 */
export function instanceOfFilterParameter(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "field" in value;
    isInstance = isInstance && "exclude" in value;
    isInstance = isInstance && "derivedFromProduct" in value;

    return isInstance;
}

export function FilterParameterFromJSON(json: any): FilterParameter {
    return FilterParameterFromJSONTyped(json, false);
}

export function FilterParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterParameter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'field': json['field'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'exclude': json['exclude'],
        'derivedFromProduct': json['derivedFromProduct'],
    };
}

export function FilterParameterToJSON(value?: FilterParameter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field': value.field,
        'value': value.value,
        'exclude': value.exclude,
        'derivedFromProduct': value.derivedFromProduct,
    };
}

