/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Fulfillment information, such as the store IDs for in-store pickup or region IDs for different shipping methods.
 * @export
 * @interface FulfillmentInfo
 */
export interface FulfillmentInfo {
    /**
     * Fulfillment type. Place where product fulfilled.
     * @type {string}
     * @memberof FulfillmentInfo
     */
    type?: string;
    /**
     * Place ids where product fulfilled (array).
     * @type {Array<string>}
     * @memberof FulfillmentInfo
     */
    placeIds?: Array<string>;
}

/**
 * Check if a given object implements the FulfillmentInfo interface.
 */
export function instanceOfFulfillmentInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FulfillmentInfoFromJSON(json: any): FulfillmentInfo {
    return FulfillmentInfoFromJSONTyped(json, false);
}

export function FulfillmentInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillmentInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'placeIds': !exists(json, 'placeIds') ? undefined : json['placeIds'],
    };
}

export function FulfillmentInfoToJSON(value?: FulfillmentInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'placeIds': value.placeIds,
    };
}

