/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of navigation.
 * @export
 */
export const NavigationType = {
    Value: 'VALUE',
    Range: 'RANGE'
} as const;
export type NavigationType = typeof NavigationType[keyof typeof NavigationType];


export function NavigationTypeFromJSON(json: any): NavigationType {
    return NavigationTypeFromJSONTyped(json, false);
}

export function NavigationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NavigationType {
    return json as NavigationType;
}

export function NavigationTypeToJSON(value?: NavigationType | null): any {
    return value as any;
}

