/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of navigation.
 * @export
 */
export const NavigationTypeDto = {
    Value: 'Value',
    Range: 'Range'
} as const;
export type NavigationTypeDto = typeof NavigationTypeDto[keyof typeof NavigationTypeDto];


export function NavigationTypeDtoFromJSON(json: any): NavigationTypeDto {
    return NavigationTypeDtoFromJSONTyped(json, false);
}

export function NavigationTypeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NavigationTypeDto {
    return json as NavigationTypeDto;
}

export function NavigationTypeDtoToJSON(value?: NavigationTypeDto | null): any {
    return value as any;
}

