/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Refinement } from './Refinement';
import {
    RefinementFromJSON,
    RefinementFromJSONTyped,
    RefinementToJSON,
} from './Refinement';

/**
 * 
 * @export
 * @interface PinnedRefinement
 */
export interface PinnedRefinement {
    /**
     * 
     * @type {string}
     * @memberof PinnedRefinement
     */
    navigation: string;
    /**
     * 
     * @type {Array<Refinement>}
     * @memberof PinnedRefinement
     */
    refinements: Array<Refinement>;
}

/**
 * Check if a given object implements the PinnedRefinement interface.
 */
export function instanceOfPinnedRefinement(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "navigation" in value;
    isInstance = isInstance && "refinements" in value;

    return isInstance;
}

export function PinnedRefinementFromJSON(json: any): PinnedRefinement {
    return PinnedRefinementFromJSONTyped(json, false);
}

export function PinnedRefinementFromJSONTyped(json: any, ignoreDiscriminator: boolean): PinnedRefinement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'navigation': json['navigation'],
        'refinements': ((json['refinements'] as Array<any>).map(RefinementFromJSON)),
    };
}

export function PinnedRefinementToJSON(value?: PinnedRefinement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'navigation': value.navigation,
        'refinements': ((value.refinements as Array<any>).map(RefinementToJSON)),
    };
}

