/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductDtoColorInfo
 */
export interface ProductDtoColorInfo {
    /**
     * Product color families (array).
     * @type {Array<string>}
     * @memberof ProductDtoColorInfo
     */
    colorFamilies?: Array<string>;
    /**
     * Product color (array).
     * @type {Array<string>}
     * @memberof ProductDtoColorInfo
     */
    colors?: Array<string>;
}

/**
 * Check if a given object implements the ProductDtoColorInfo interface.
 */
export function instanceOfProductDtoColorInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductDtoColorInfoFromJSON(json: any): ProductDtoColorInfo {
    return ProductDtoColorInfoFromJSONTyped(json, false);
}

export function ProductDtoColorInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDtoColorInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'colorFamilies': !exists(json, 'colorFamilies') ? undefined : json['colorFamilies'],
        'colors': !exists(json, 'colors') ? undefined : json['colors'],
    };
}

export function ProductDtoColorInfoToJSON(value?: ProductDtoColorInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'colorFamilies': value.colorFamilies,
        'colors': value.colors,
    };
}

