/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductDtoRetrievableFields
 */
export interface ProductDtoRetrievableFields {
    /**
     * Paths for retrievable fields (array).
     * @type {Array<string>}
     * @memberof ProductDtoRetrievableFields
     */
    paths?: Array<string>;
}

/**
 * Check if a given object implements the ProductDtoRetrievableFields interface.
 */
export function instanceOfProductDtoRetrievableFields(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductDtoRetrievableFieldsFromJSON(json: any): ProductDtoRetrievableFields {
    return ProductDtoRetrievableFieldsFromJSONTyped(json, false);
}

export function ProductDtoRetrievableFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDtoRetrievableFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paths': !exists(json, 'paths') ? undefined : json['paths'],
    };
}

export function ProductDtoRetrievableFieldsToJSON(value?: ProductDtoRetrievableFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'paths': value.paths,
    };
}

