/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const QueryPatternTriggerType = {
    Contains: 'CONTAINS',
    EndsWith: 'ENDS_WITH',
    Regex: 'REGEX',
    StartsWith: 'STARTS_WITH',
    Matches: 'MATCHES'
} as const;
export type QueryPatternTriggerType = typeof QueryPatternTriggerType[keyof typeof QueryPatternTriggerType];


export function QueryPatternTriggerTypeFromJSON(json: any): QueryPatternTriggerType {
    return QueryPatternTriggerTypeFromJSONTyped(json, false);
}

export function QueryPatternTriggerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryPatternTriggerType {
    return json as QueryPatternTriggerType;
}

export function QueryPatternTriggerTypeToJSON(value?: QueryPatternTriggerType | null): any {
    return value as any;
}

