/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Range
 */
export interface Range {
    /**
     * 
     * @type {number}
     * @memberof Range
     */
    low: number;
    /**
     * 
     * @type {number}
     * @memberof Range
     */
    high: number;
}

/**
 * Check if a given object implements the Range interface.
 */
export function instanceOfRange(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "low" in value;
    isInstance = isInstance && "high" in value;

    return isInstance;
}

export function RangeFromJSON(json: any): Range {
    return RangeFromJSONTyped(json, false);
}

export function RangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Range {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'low': json['low'],
        'high': json['high'],
    };
}

export function RangeToJSON(value?: Range | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'low': value.low,
        'high': value.high,
    };
}

