/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RangeFilter
 */
export interface RangeFilter {
    /**
     * Field the range applies to.
     * @type {string}
     * @memberof RangeFilter
     */
    field: string;
    /**
     * Range of values the field value can be.
     * @type {any}
     * @memberof RangeFilter
     */
    range: any | null;
}

/**
 * Check if a given object implements the RangeFilter interface.
 */
export function instanceOfRangeFilter(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "field" in value;
    isInstance = isInstance && "range" in value;

    return isInstance;
}

export function RangeFilterFromJSON(json: any): RangeFilter {
    return RangeFilterFromJSONTyped(json, false);
}

export function RangeFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): RangeFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'field': json['field'],
        'range': json['range'],
    };
}

export function RangeFilterToJSON(value?: RangeFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field': value.field,
        'range': value.range,
    };
}

