/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Refinement
 */
export interface Refinement {
    /**
     * 
     * @type {string}
     * @memberof Refinement
     */
    value: string;
    /**
     * 
     * @type {number}
     * @memberof Refinement
     */
    priority: number;
}

/**
 * Check if a given object implements the Refinement interface.
 */
export function instanceOfRefinement(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "priority" in value;

    return isInstance;
}

export function RefinementFromJSON(json: any): Refinement {
    return RefinementFromJSONTyped(json, false);
}

export function RefinementFromJSONTyped(json: any, ignoreDiscriminator: boolean): Refinement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
        'priority': json['priority'],
    };
}

export function RefinementToJSON(value?: Refinement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'priority': value.priority,
    };
}

