/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchResultsStats
 */
export interface SearchResultsStats {
    /**
     * Count of suggested sentences in response.
     * @type {number}
     * @memberof SearchResultsStats
     */
    searchCount?: number;
    /**
     * Time in milliseconds taken by autocomplete service to handle request and send response.
     * @type {number}
     * @memberof SearchResultsStats
     */
    autocompleteResponse?: number;
    /**
     * Count of extended attributes in autocomplete response.
     * @type {number}
     * @memberof SearchResultsStats
     */
    extendedAttributesCount?: number;
    /**
     * Time in milliseconds taken by application to enrich response with extended attributes.
     * @type {number}
     * @memberof SearchResultsStats
     */
    extendedAttributesResponse?: number;
}

/**
 * Check if a given object implements the SearchResultsStats interface.
 */
export function instanceOfSearchResultsStats(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchResultsStatsFromJSON(json: any): SearchResultsStats {
    return SearchResultsStatsFromJSONTyped(json, false);
}

export function SearchResultsStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultsStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'searchCount': !exists(json, 'searchCount') ? undefined : json['searchCount'],
        'autocompleteResponse': !exists(json, 'autocompleteResponse') ? undefined : json['autocompleteResponse'],
        'extendedAttributesCount': !exists(json, 'extendedAttributesCount') ? undefined : json['extendedAttributesCount'],
        'extendedAttributesResponse': !exists(json, 'extendedAttributesResponse') ? undefined : json['extendedAttributesResponse'],
    };
}

export function SearchResultsStatsToJSON(value?: SearchResultsStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'searchCount': value.searchCount,
        'autocompleteResponse': value.autocompleteResponse,
        'extendedAttributesCount': value.extendedAttributesCount,
        'extendedAttributesResponse': value.extendedAttributesResponse,
    };
}

