/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RuleConfiguration } from './RuleConfiguration';
import {
    RuleConfigurationFromJSON,
    RuleConfigurationFromJSONTyped,
    RuleConfigurationToJSON,
} from './RuleConfiguration';

/**
 * 
 * @export
 * @interface SearchRequestDtoOverwrites
 */
export interface SearchRequestDtoOverwrites {
    /**
     * 
     * @type {Array<RuleConfiguration>}
     * @memberof SearchRequestDtoOverwrites
     */
    rules: Array<RuleConfiguration>;
}

/**
 * Check if a given object implements the SearchRequestDtoOverwrites interface.
 */
export function instanceOfSearchRequestDtoOverwrites(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rules" in value;

    return isInstance;
}

export function SearchRequestDtoOverwritesFromJSON(json: any): SearchRequestDtoOverwrites {
    return SearchRequestDtoOverwritesFromJSONTyped(json, false);
}

export function SearchRequestDtoOverwritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRequestDtoOverwrites {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rules': ((json['rules'] as Array<any>).map(RuleConfigurationFromJSON)),
    };
}

export function SearchRequestDtoOverwritesToJSON(value?: SearchRequestDtoOverwrites | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rules': ((value.rules as Array<any>).map(RuleConfigurationToJSON)),
    };
}

