/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BiasingProfileDto } from './BiasingProfileDto';
import {
    BiasingProfileDtoFromJSON,
    BiasingProfileDtoFromJSONTyped,
    BiasingProfileDtoToJSON,
} from './BiasingProfileDto';
import type { CustomParameterDto } from './CustomParameterDto';
import {
    CustomParameterDtoFromJSON,
    CustomParameterDtoFromJSONTyped,
    CustomParameterDtoToJSON,
} from './CustomParameterDto';
import type { SearchRequestDtoOverwrites } from './SearchRequestDtoOverwrites';
import {
    SearchRequestDtoOverwritesFromJSON,
    SearchRequestDtoOverwritesFromJSONTyped,
    SearchRequestDtoOverwritesToJSON,
} from './SearchRequestDtoOverwrites';
import type { SelectedRefinementDto } from './SelectedRefinementDto';
import {
    SelectedRefinementDtoFromJSON,
    SelectedRefinementDtoFromJSONTyped,
    SelectedRefinementDtoToJSON,
} from './SelectedRefinementDto';
import type { SortDto } from './SortDto';
import {
    SortDtoFromJSON,
    SortDtoFromJSONTyped,
    SortDtoToJSON,
} from './SortDto';
import type { SpellCorrectionMode } from './SpellCorrectionMode';
import {
    SpellCorrectionModeFromJSON,
    SpellCorrectionModeFromJSONTyped,
    SpellCorrectionModeToJSON,
} from './SpellCorrectionMode';

/**
 * Request that should be populated to configure a search API call, made by the client on behalf of a shopper.
 * @export
 * @interface SearchRequestDto
 */
export interface SearchRequestDto {
    /**
     * Base textual search query.
     * @type {string}
     * @memberof SearchRequestDto
     */
    query?: string | null;
    /**
     * Area name the search is being performed in.
     * @type {string}
     * @memberof SearchRequestDto
     */
    area?: string | null;
    /**
     * Name of collection in project configuration setting which is mapped to the google retail backend.
     * @type {string}
     * @memberof SearchRequestDto
     */
    collection?: string | null;
    /**
     * Unique identifier identifying the shopper. Will be autogenerated if not provided.
     * @type {string}
     * @memberof SearchRequestDto
     */
    visitorId?: string | null;
    /**
     * 
     * @type {Array<SelectedRefinementDto>}
     * @memberof SearchRequestDto
     */
    refinements: Array<SelectedRefinementDto>;
    /**
     * The number of products to be returned on each page.
     * @type {number}
     * @memberof SearchRequestDto
     */
    pageSize?: number | null;
    /**
     * Where in the list of products to begin the page.
     * @type {number}
     * @memberof SearchRequestDto
     */
    skip?: number | null;
    /**
     * Name of a biasing profile which should be applied to the search. Takes priority over area default.
     * @type {string}
     * @memberof SearchRequestDto
     */
    biasingProfile?: string | null;
    /**
     * 
     * @type {BiasingProfileDto}
     * @memberof SearchRequestDto
     */
    biasing: BiasingProfileDto | null;
    /**
     * 
     * @type {Array<CustomParameterDto>}
     * @memberof SearchRequestDto
     */
    customUrlParams: Array<CustomParameterDto>;
    /**
     * 
     * @type {Array<SortDto>}
     * @memberof SearchRequestDto
     */
    sorts: Array<SortDto>;
    /**
     * Set of navigation fields to include in the search result. Cannot be set if 'excludedNavigations' is set.
     * @type {Array<string>}
     * @memberof SearchRequestDto
     */
    includedNavigations?: Array<string> | null;
    /**
     * Set of navigation fields to exclude in the search result. Cannot be set if 'includedNavigations' is set.
     * @type {Array<string>}
     * @memberof SearchRequestDto
     */
    excludedNavigations?: Array<string> | null;
    /**
     * Set the specifications of dynamically generated facets.
     * @type {boolean}
     * @memberof SearchRequestDto
     */
    dynamicFacet?: boolean | null;
    /**
     * Set the variant rollup keys.
     * @type {Array<string>}
     * @memberof SearchRequestDto
     */
    variantRollupKeys?: Array<string> | null;
    /**
     * Set of the prefilter specifications value.
     * @type {string}
     * @memberof SearchRequestDto
     */
    preFilter?: string | null;
    /**
     * Name of site filter. If not specified, the specified area's default site will be applied if configured in Command Center. To not use default specify empty value i.e."".  If the site doesn't exist then the search will execute without the site filter and a warning will be provided.
     * @type {string}
     * @memberof SearchRequestDto
     */
    site?: string | null;
    /**
     * List with fields which should be included in metadata object associated with each record in response.
     * @type {Array<string>}
     * @memberof SearchRequestDto
     */
    responseMask?: Array<string> | null;
    /**
     * The categories associated with a category page. Required for category navigation queries to achieve good search quality. To represent full path of category, use '>' sign to separate different hierarchies. If '>' is part of the category name, please replace it with other character(s).Max item length = 1.
     * @type {Array<string>}
     * @memberof SearchRequestDto
     */
    pageCategories?: Array<string> | null;
    /**
     * 
     * @type {SpellCorrectionMode}
     * @memberof SearchRequestDto
     */
    spellCorrectionMode?: SpellCorrectionMode | null;
    /**
     * When a shopper uses an ambiguous or a multi-word search phrase, they can get an empty response. After turning on include expanded results, Retail Search analyzes the request and returns the expanded list of products based on the parsed search query. For example, if you search "Google Pixel 5" without query expansion, you might only get "google_pixel_5" in the result. With query expansion, you might get "google_pixel_4a_with_5g", "google_pixel_4a" and "google_pixel_5_case" as well.The default value is configured in the tenant settings or true if there is no such setting
     * @type {boolean}
     * @memberof SearchRequestDto
     */
    includeExpandedResults?: boolean | null;
    /**
     * This configuration depends on include expanded results settings. If this field is set to true,unexpanded products are always at the top of the search results, followed  by the expanded results. Default value: true
     * @type {boolean}
     * @memberof SearchRequestDto
     */
    pinUnexpandedResults?: boolean | null;
    /**
     * Enable additional debug info in response.
     * 
     * Note: attaching debug info significantly affects performance.
     * Is not supposed to be used for large requests.
     * @type {boolean}
     * @memberof SearchRequestDto
     */
    debug?: boolean | null;
    /**
     * Maximum of facet values that should be returned for this facet. If not specified, defaults to 20.
     * The maximum allowed value is 300. Values above 300 will be coerced to 300.
     * 
     * If this field is negative, an INVALID_ARGUMENT is returned.
     * 
     * This limit (300) is configured on Google side, but Google have an ability to change it for specific project.
     * @type {number}
     * @memberof SearchRequestDto
     */
    facetLimit?: number | null;
    /**
     * Highly recommended for logged-in users. Unique identifier for logged-in user,
     * such as a user name. Don't set for anonymous users.
     * 
     * Don't set the field to the same fixed ID for different users. This mixes
     * the event history of those users together, which results in degraded
     * model quality.
     * 
     * The field must be a UTF-8 encoded string with a length limit of 128
     * characters.
     * @type {string}
     * @memberof SearchRequestDto
     */
    loginId?: string | null;
    /**
     * 
     * @type {SearchRequestDtoOverwrites}
     * @memberof SearchRequestDto
     */
    overwrites?: SearchRequestDtoOverwrites | null;
}

/**
 * Check if a given object implements the SearchRequestDto interface.
 */
export function instanceOfSearchRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "refinements" in value;
    isInstance = isInstance && "biasing" in value;
    isInstance = isInstance && "customUrlParams" in value;
    isInstance = isInstance && "sorts" in value;

    return isInstance;
}

export function SearchRequestDtoFromJSON(json: any): SearchRequestDto {
    return SearchRequestDtoFromJSONTyped(json, false);
}

export function SearchRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'query': !exists(json, 'query') ? undefined : json['query'],
        'area': !exists(json, 'area') ? undefined : json['area'],
        'collection': !exists(json, 'collection') ? undefined : json['collection'],
        'visitorId': !exists(json, 'visitorId') ? undefined : json['visitorId'],
        'refinements': ((json['refinements'] as Array<any>).map(SelectedRefinementDtoFromJSON)),
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'skip': !exists(json, 'skip') ? undefined : json['skip'],
        'biasingProfile': !exists(json, 'biasingProfile') ? undefined : json['biasingProfile'],
        'biasing': BiasingProfileDtoFromJSON(json['biasing']),
        'customUrlParams': ((json['customUrlParams'] as Array<any>).map(CustomParameterDtoFromJSON)),
        'sorts': ((json['sorts'] as Array<any>).map(SortDtoFromJSON)),
        'includedNavigations': !exists(json, 'includedNavigations') ? undefined : json['includedNavigations'],
        'excludedNavigations': !exists(json, 'excludedNavigations') ? undefined : json['excludedNavigations'],
        'dynamicFacet': !exists(json, 'dynamicFacet') ? undefined : json['dynamicFacet'],
        'variantRollupKeys': !exists(json, 'variantRollupKeys') ? undefined : json['variantRollupKeys'],
        'preFilter': !exists(json, 'preFilter') ? undefined : json['preFilter'],
        'site': !exists(json, 'site') ? undefined : json['site'],
        'responseMask': !exists(json, 'responseMask') ? undefined : json['responseMask'],
        'pageCategories': !exists(json, 'pageCategories') ? undefined : json['pageCategories'],
        'spellCorrectionMode': !exists(json, 'spellCorrectionMode') ? undefined : SpellCorrectionModeFromJSON(json['spellCorrectionMode']),
        'includeExpandedResults': !exists(json, 'includeExpandedResults') ? undefined : json['includeExpandedResults'],
        'pinUnexpandedResults': !exists(json, 'pinUnexpandedResults') ? undefined : json['pinUnexpandedResults'],
        'debug': !exists(json, 'debug') ? undefined : json['debug'],
        'facetLimit': !exists(json, 'facetLimit') ? undefined : json['facetLimit'],
        'loginId': !exists(json, 'loginId') ? undefined : json['loginId'],
        'overwrites': !exists(json, 'overwrites') ? undefined : SearchRequestDtoOverwritesFromJSON(json['overwrites']),
    };
}

export function SearchRequestDtoToJSON(value?: SearchRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'query': value.query,
        'area': value.area,
        'collection': value.collection,
        'visitorId': value.visitorId,
        'refinements': ((value.refinements as Array<any>).map(SelectedRefinementDtoToJSON)),
        'pageSize': value.pageSize,
        'skip': value.skip,
        'biasingProfile': value.biasingProfile,
        'biasing': BiasingProfileDtoToJSON(value.biasing),
        'customUrlParams': ((value.customUrlParams as Array<any>).map(CustomParameterDtoToJSON)),
        'sorts': ((value.sorts as Array<any>).map(SortDtoToJSON)),
        'includedNavigations': value.includedNavigations,
        'excludedNavigations': value.excludedNavigations,
        'dynamicFacet': value.dynamicFacet,
        'variantRollupKeys': value.variantRollupKeys,
        'preFilter': value.preFilter,
        'site': value.site,
        'responseMask': value.responseMask,
        'pageCategories': value.pageCategories,
        'spellCorrectionMode': SpellCorrectionModeToJSON(value.spellCorrectionMode),
        'includeExpandedResults': value.includeExpandedResults,
        'pinUnexpandedResults': value.pinUnexpandedResults,
        'debug': value.debug,
        'facetLimit': value.facetLimit,
        'loginId': value.loginId,
        'overwrites': SearchRequestDtoOverwritesToJSON(value.overwrites),
    };
}

