/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Metadata relating to the search results, or how they were generated.
 * @export
 * @interface SearchMetadataDto
 */
export interface SearchMetadataDto {
    /**
     * Token to assist beacon collectors in correlating searches to user events.
     * @type {string}
     * @memberof SearchMetadataDto
     */
    searchAttributionToken?: string | null;
    /**
     * Were the search results from a previous call.
     * @type {boolean}
     * @memberof SearchMetadataDto
     */
    cached?: boolean;
    /**
     * Total time spent performing the Google search in milliseconds.
     * @type {number}
     * @memberof SearchMetadataDto
     */
    totalTime?: number;
}

/**
 * Check if a given object implements the SearchMetadataDto interface.
 */
export function instanceOfSearchMetadataDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchMetadataDtoFromJSON(json: any): SearchMetadataDto {
    return SearchMetadataDtoFromJSONTyped(json, false);
}

export function SearchMetadataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchMetadataDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'searchAttributionToken': !exists(json, 'searchAttributionToken') ? undefined : json['searchAttributionToken'],
        'cached': !exists(json, 'cached') ? undefined : json['cached'],
        'totalTime': !exists(json, 'totalTime') ? undefined : json['totalTime'],
    };
}

export function SearchMetadataDtoToJSON(value?: SearchMetadataDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'searchAttributionToken': value.searchAttributionToken,
        'cached': value.cached,
        'totalTime': value.totalTime,
    };
}

