/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SortDtoOrderDto } from './SortDtoOrderDto';
import {
    SortDtoOrderDtoFromJSON,
    SortDtoOrderDtoFromJSONTyped,
    SortDtoOrderDtoToJSON,
} from './SortDtoOrderDto';

/**
 * Order the returned products should appear on the page.
 * @export
 * @interface SortDto
 */
export interface SortDto {
    /**
     * Field the order will be applied to.
     * @type {string}
     * @memberof SortDto
     */
    field: string;
    /**
     * 
     * @type {SortDtoOrderDto}
     * @memberof SortDto
     */
    order: SortDtoOrderDto | null;
}

/**
 * Check if a given object implements the SortDto interface.
 */
export function instanceOfSortDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "field" in value;
    isInstance = isInstance && "order" in value;

    return isInstance;
}

export function SortDtoFromJSON(json: any): SortDto {
    return SortDtoFromJSONTyped(json, false);
}

export function SortDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'field': json['field'],
        'order': SortDtoOrderDtoFromJSON(json['order']),
    };
}

export function SortDtoToJSON(value?: SortDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field': value.field,
        'order': SortDtoOrderDtoToJSON(value.order),
    };
}

