/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Order the products will appear in
 * @export
 */
export const SortDtoOrderDto = {
    Ascending: 'Ascending',
    Descending: 'Descending'
} as const;
export type SortDtoOrderDto = typeof SortDtoOrderDto[keyof typeof SortDtoOrderDto];


export function SortDtoOrderDtoFromJSON(json: any): SortDtoOrderDto {
    return SortDtoOrderDtoFromJSONTyped(json, false);
}

export function SortDtoOrderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortDtoOrderDto {
    return json as SortDtoOrderDto;
}

export function SortDtoOrderDtoToJSON(value?: SortDtoOrderDto | null): any {
    return value as any;
}

