/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Timestamp info with seconds and nanos.
 * @export
 * @interface Timestamp
 */
export interface Timestamp {
    /**
     * Timestamp seconds.
     * @type {number}
     * @memberof Timestamp
     */
    seconds?: number;
    /**
     * Timestamp nanos.
     * @type {number}
     * @memberof Timestamp
     */
    nanos?: number;
}

/**
 * Check if a given object implements the Timestamp interface.
 */
export function instanceOfTimestamp(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TimestampFromJSON(json: any): Timestamp {
    return TimestampFromJSONTyped(json, false);
}

export function TimestampFromJSONTyped(json: any, ignoreDiscriminator: boolean): Timestamp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'seconds': !exists(json, 'seconds') ? undefined : json['seconds'],
        'nanos': !exists(json, 'nanos') ? undefined : json['nanos'],
    };
}

export function TimestampToJSON(value?: Timestamp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'seconds': value.seconds,
        'nanos': value.nanos,
    };
}

