/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ValueFilterValueFilterType = {
    Textual: 'TEXTUAL',
    Numeric: 'NUMERIC'
} as const;
export type ValueFilterValueFilterType = typeof ValueFilterValueFilterType[keyof typeof ValueFilterValueFilterType];


export function ValueFilterValueFilterTypeFromJSON(json: any): ValueFilterValueFilterType {
    return ValueFilterValueFilterTypeFromJSONTyped(json, false);
}

export function ValueFilterValueFilterTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValueFilterValueFilterType {
    return json as ValueFilterValueFilterType;
}

export function ValueFilterValueFilterTypeToJSON(value?: ValueFilterValueFilterType | null): any {
    return value as any;
}

