/* tslint:disable */
/* eslint-disable */
/**
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Define type of content which is can be stored in zone.
 * @export
 */
export const ZoneDtoType = {
    Content: 'Content',
    RichContent: 'Rich_Content',
    Products: 'Products',
    GeneratedContent: 'Generated_Content'
} as const;
export type ZoneDtoType = typeof ZoneDtoType[keyof typeof ZoneDtoType];


export function ZoneDtoTypeFromJSON(json: any): ZoneDtoType {
    return ZoneDtoTypeFromJSONTyped(json, false);
}

export function ZoneDtoTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZoneDtoType {
    return json as ZoneDtoType;
}

export function ZoneDtoTypeToJSON(value?: ZoneDtoType | null): any {
    return value as any;
}

